/* eslint-disable @next/next/no-sync-scripts */
// "use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import {Providers} from "./Provider"
import {GoogleOAuthProvider} from "@react-oauth/google"
// import { GoogleOAuthProvider} from '@react-oauth/google';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SpiritSpark",
  icons:{
    icon:[
      'favicon-16x16.png'
    ],
    apple:[
      'apple-touch-icon.png'
    ],
    shortcut:[
      '/apple-touch-icon.png'
    ]
  },
  manifest:'/site.webmanifest',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   
    <html lang="en">
      <head>
      </head>
      <body className={` ${inter.className}`}>
        <GoogleOAuthProvider clientId={`${process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}`}>
        <Providers>
         <Toaster position="top-center" /> 
        {children}
        </Providers>
        </GoogleOAuthProvider>
        </body>
        
    </html>
  );
}
